### ISSUE TITLE
Migrate Continuous Documentation from Vercel to Readthedocs

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt-examples#13]
As indicated by @seisman, we need to migrate from Vercel to Readthedocs.

I do not understand much how to do it so I will follow the steps here (https://github.com/GenericMappingTools/pygmt/pull/1859) to do it and the [files](https://github.com/GenericMappingTools/pygmt/pull/1859/files) 

As far as I understand I need to:
- Delete package.json and vercel.json.
- Add .readthedocs.yaml and ci/requirements/docs.yml
- Edit [conf.py](https://github.com/GenericMappingTools/gmt-examples/blob/main/docs/conf.py)?

Please let me know if this is ok.

**Comment by seisman** [comment]
> * Delete package.json and vercel.json.

Yes

> * Add .readthedocs.yaml and ci/requirements/docs.yml

`ci/requirements/docs.yml` is not needed here, because we have https://github.com/GenericMappingTools/gmt-examples/blob/main/environment.yml.

> * Edit [conf.py](https://github.com/GenericMappingTools/gmt-examples/blob/main/docs/conf.py)?

Yes.

You also need to sign up ReadTheDocs (https://readthedocs.org/accounts/login/?next=/dashboard/), import the `gmt-examples` repository, and check the "Build pull requests for this project:" box in the settings.

**Comment by Esteban82** [comment]
> > * Edit [conf.py](https://github.com/GenericMappingTools/gmt-examples/blob/main/docs/conf.py)?
> 
> Yes.

What should I update in conf.py? The file here is quite different from the pygmt file.

**Comment by seisman** [comment]
> > > * Edit [conf.py](https://github.com/GenericMappingTools/gmt-examples/blob/main/docs/conf.py)?
> > 
> > 
> > Yes.
> 
> What should I update in conf.py? The file here is quite different from the pygmt file.

Just add `html_baseurl="https://www.generic-mapping-tools.org/gmt-examples/"`

**Comment by Esteban82** [comment]
> You also need to sign up ReadTheDocs (https://readthedocs.org/accounts/login/?next=/dashboard/), import the `gmt-examples` repository, and check the "Build pull requests for this project:" box in the settings.

Could I do it? Or only the maintainers (in [this list](https://github.com/GenericMappingTools/bus-factors?tab=readme-ov-file#readthedocs)) can?

**Comment by seisman** [comment]
> > You also need to sign up ReadTheDocs (https://readthedocs.org/accounts/login/?next=/dashboard/), import the `gmt-examples` repository, and check the "Build pull requests for this project:" box in the settings.
> 
> Could I do it? Or only the maintainers (in [this list](https://github.com/GenericMappingTools/bus-factors?tab=readme-ov-file#readthedocs)) can?

I think you can. Then you can add others as maintainers. Or I can do it.

**Comment by seisman** [comment]
> > Or I can do it.
> 
> Yes, please do it. Thanks

Done.

**Comment by Esteban82** [comment]
> `ci/requirements/docs.yml` is not needed here, because we have https://github.com/GenericMappingTools/gmt-examples/blob/main/environment.yml.
> 
> >

Ok. So, I guess that I have to use this `environment: environment.yml ` in the line 26 of [.readthedocs.yaml](https://github.com/GenericMappingTools/pygmt/pull/1859/files#diff-03efc769b870804394632e45d7885272b44c16939517fb31c9d7c614d2ffae57). Right?

**Comment by seisman** [comment]
> > `ci/requirements/docs.yml` is not needed here, because we have https://github.com/GenericMappingTools/gmt-examples/blob/main/environment.yml.
> > >
> 
> Ok. So, I guess that I have to use this `environment: environment.yml ` in the line 26 of [.readthedocs.yaml](https://github.com/GenericMappingTools/pygmt/pull/1859/files#diff-03efc769b870804394632e45d7885272b44c16939517fb31c9d7c614d2ffae57). Right?

yes

**Comment by seisman** [comment]
> > > > Or I can do it.
> > > 
> > > 
> > > Yes, please do it. Thanks
> > 
> > 
> > Done.
> 
> Great. There is nothing else to do in ReadTheDocs, is there?

i'm not sure. please try and we will know if there are errors.
