### ISSUE TITLE
Use data created on the fly for the tutorials in rst file

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt-examples#20]
I am making a tutorial about lines. I want to use some data created on the fly (as in the [pygmt](https://www.pygmt.org/latest/tutorials/basics/lines.html)).

How can I do it? @seisman do you know?

I try the following but it fails:

```
     .. gmtplot::

      gmt begin line2 png
         gmt plot -Ra -JX10c -Baf -W <<- EOF
         1,8
         1,8
         EOF
      gmt end show
```
     
I think this are the messages related to those lines:

```
Exception occurred:
  File "/home/federico/.local/lib/python3.10/site-packages/sphinx_gmt/gmtplot.py", line 199, in eval_bash
    raise RuntimeError(
RuntimeError: GMT bash failed:
STDOUT: {proc.stdout.decode("utf-8")}
STDERR: {proc.stderr.decode("utf-8")}
The full traceback has been saved in /tmp/sphinx-err-8jhsedt1.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:20: html] Error 2
```

**Comment by seisman** [comment]
Maybe the indentation is incorrect? Try this:
```
     .. gmtplot::

        gmt begin line2 png
            gmt plot -Ra -JX10c -Baf -W <<- EOF
            1,8
            1,8
            EOF
        gmt end show
```

**Comment by Esteban82** [comment]
No, it didn't work. The indentaion is fine. I try with data from the cache and it worked.

```
     .. gmtplot::

        gmt begin line2 png
            gmt plot -Ra -JX10c -Baf -W @tut_data.txt 
        gmt end show  
```

**Comment by seisman** [comment]
It should be either
```
     .. gmtplot::

        gmt begin line2 png
            gmt plot -R0/10/0/10 -JX10c -Baf -W <<- 'EOF'
            1,8
            1,8
            EOF
        gmt end show
```
or 
```
     .. gmtplot::

        gmt begin line2 png
            gmt plot -R0/10/0/10 -JX10c -Baf -W <<- 'EOF'
            1,8
            1,8
        EOF
        gmt end show
```

**Comment by Esteban82** [comment]
It didn't work on my pc.

I got this:

![image](https://github.com/GenericMappingTools/gmt-examples/assets/17908951/4d2e4ebb-57ba-40cc-be95-b1cd7fcb4a67)

**Comment by joa-quim** [comment]
Remember that that those _EOF_ constructs do not work on pure Windows, which for a beginner's tutorial is not the best thing. I would prefer to have examples that are OS agnostic.

**Comment by Esteban82** [comment]
Ok, I agree. 

So what method should we use? tell the users to create a txt file with the data?

**Comment by joa-quim** [comment]
It's not pretty but we can use a double `echo x1 y1 > file;  echo x2 y2 >> file`. But ideally should be some sort of `gmtmath` command.

**Comment by seisman** [comment]
> Remember that that those _EOF_ constructs do not work on pure Windows, which for a beginner's tutorial is not the best thing. I would prefer to have examples that are OS agnostic.

It's possible to use Sphinx-design's `tab` directive to have scripts for both Unix and Windows.

> But ideally should be some sort of `gmtmath` command.

`gmtmath` is likely one of the most complicated modules that users rarely use, so it's not a good idea to use it in tutorials.

**Comment by Esteban82** [comment]
> It's not pretty but we can use a double `echo x1 y1 > file; echo x2 y2 >> file`.

This worked. I would prefer a method with `cat`
