### ISSUE TITLE
How to add videos to the examples?

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/gmt-examples#36]
I am making a tutorial about animations. I don't know how to include a video.

I think that the best approach is to upload the videos on youtube and add the link. Do you agree? 

I try to include a youtube video (as in [animation 1](https://github.com/GenericMappingTools/gmt/edit/master/doc/rst/source/animations/anim01.rst)) but it didn't work

```
..  youtube:: NjSDpQ5S3FM
    :width: 100%

```

**Comment by seisman** [comment]
Need to add the `sphinxcontribu-youtube` extension following https://sphinxcontrib-youtube.readthedocs.io/en/latest/usage.html

**Comment by Esteban82** [comment]
Where should I add `sphinxcontribu-youtube` ? In [requirements.txt](https://github.com/GenericMappingTools/gmt-examples/blob/main/requirements.txt') ? 

I did it. Then I run `python -m pip install -r requirements.txt `again and I got this error:
```
ERROR: Could not find a version that satisfies the requirement sphinxcontribu-youtube (from versions: none)
ERROR: No matching distribution found for sphinxcontribu-youtube
```

Is it ok what I did? How can I solve that error?

**Comment by Esteban82** [comment]
Update: 

I use this (`sphinxcontrib-youtube==1.4.1`) instead and the error dissapear but now, when I run `make html` I got: 

```
/home/esteban82/Github/GenericMappingTools/gmt-examples/docs/tutorials/advance/movie.rst:45: ERROR: Unknown directive type "youtube".

..  youtube:: NjSDpQ5S3FM
    :width: 100%
```

**Comment by seisman** [comment]
You also need to add it to `conf.py`.

xref: https://sphinxcontrib-youtube.readthedocs.io/en/latest/usage.html#configuration

**Comment by Esteban82** [comment]
> You also need to add it to `conf.py`.
> 
> xref: https://sphinxcontrib-youtube.readthedocs.io/en/latest/usage.html#configuration

Thanks. Now it is working.

**Comment by Esteban82** [comment]
I have doubts whether it is the best idea to add youtube videos. If there is no better alternative. What do you think?

**Comment by seisman** [comment]
I don't have an alternative solution for it.

**Comment by Esteban82** [comment]
Mm ok. Doubt solved.
